appname: "iamhere"
version: "0.0.1"

appconfig:
   host:           ""
   port:           "9090"
   loggerPrefix:   "iamhere"
   enableDebug:    true
   enableSSL:      false
   enableDumpLog:  false
   logPath:        "/var/log/iamhere/"

apiconfig:
   prefix:         "/api"
   version:        "/v1"
   secret:         "V85ZzBeTnzpsHyjQX4zukbQ8qqtju9y2aDM55VWxAH9Qop19poekx3xkcDVvrD0y"
   randomItemLimit: 20
   mixacessDistanceLimit: 2000 #2km
   bodySizeLimit:  "1K"
   accounts:
       group:      "/accounts"
   login:
       group:      "/login"
   messages:
       group:      "/messages"
   areas:
       group:      "/areas"
   trails: 
       group:      "/trails"

database:
   name:     "iamhere"
   user:     "wangjianging"
   password: "admin"
   host:     "localhost"
   port:     "27017"

externalurl:
   wechat:
       url: "https://api.weixin.qq.com/sns/jscode2session"
       granttype: "authorization_code"

